apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: movie-agent
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/maxScale: "2"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/apa-bd/cloud-run-source-deploy/movie-agent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: TMDB_API_KEY
              value: PLACEHOLDER
            - name: CLAUDE_CODE_USE_VERTEX
              value: "1"
            - name: CLOUD_ML_REGION
              value: PLACEHOLDER
            - name: ANTHROPIC_VERTEX_PROJECT_ID
              value: PLACEHOLDER
            - name: ANTHROPIC_VERTEX_BASE_URL
              value: PLACEHOLDER
            - name: CLAUDE_CODE_SKIP_VERTEX_AUTH
              value: "1"
            - name: ANTHROPIC_AUTH_TOKEN
              value: PLACEHOLDER
            - name: ANTHROPIC_MODEL
              value: PLACEHOLDER
            - name: GCS_BUCKET_NAME
              value: PLACEHOLDER
            - name: APP_BASE_URL
              value: https://movie-agent-389635339946.us-central1.run.app
