apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: movie-agent
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/maxScale: "2"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: us-central1-docker.pkg.dev/apa-bd/cloud-run-source-deploy/movie-agent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: TMDB_API_KEY
              value: PLACEHOLDER
